# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookmarkUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(243, 83)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget_2 = QtWidgets.QWidget(self.widget)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(40, 20))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(180, 20))
        self.tabWidget_2.setStyleSheet("QWidget{\n"
"    background-color:rgb(35, 34, 39);\n"
"    color:rgb(170, 170, 170);\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    border-bottom-left-radius:5px;        \n"
"    border-bottom-right-radius:5px;\n"
"    padding:2px;\n"
"}")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabLabel = QtWidgets.QLabel(self.tabWidget_2)
        self.tabLabel.setMinimumSize(QtCore.QSize(10, 20))
        self.tabLabel.setMaximumSize(QtCore.QSize(150, 25))
        self.tabLabel.setText("test")
        self.tabLabel.setObjectName("tabLabel")
        self.horizontalLayout_2.addWidget(self.tabLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.tabWidget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
