# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\webPageUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFontDatabase
from extensions import BrowserUtilities


class Ui_wpWidget(object):
    def setupUi(self, wpWidget):
        QFontDatabase.addApplicationFont(BrowserUtilities.resource_path("Fonts\\dripicons-v2.ttf"))

        wpWidget.setObjectName("wpWidget")
        wpWidget.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wpWidget.sizePolicy().hasHeightForWidth())
        wpWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(wpWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wpWidget_2 = QtWidgets.QWidget(wpWidget)
        self.wpWidget_2.setObjectName("wpWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wpWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wpWidget_3 = QtWidgets.QWidget(self.wpWidget_2)
        self.wpWidget_3.setMinimumSize(QtCore.QSize(0, 40))
        self.wpWidget_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wpWidget_3.setStyleSheet("QWidget#wpWidget_3{\n"
"    background-color:rgb(35, 34, 39);\n"
"}")
        self.wpWidget_3.setObjectName("wpWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wpWidget_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 18, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wpWidget_5 = QtWidgets.QWidget(self.wpWidget_3)
        self.wpWidget_5.setMinimumSize(QtCore.QSize(0, 40))
        self.wpWidget_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wpWidget_5.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:17px;\n"
"    font-family:dripicons-v2;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(144, 144, 144, 30);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.wpWidget_5.setObjectName("wpWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wpWidget_5)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wpPushButton = QtWidgets.QPushButton(self.wpWidget_5)
        self.wpPushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.wpPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.wpPushButton.setObjectName("wpPushButton")
        self.horizontalLayout.addWidget(self.wpPushButton)
        self.wpPushButton_2 = QtWidgets.QPushButton(self.wpWidget_5)
        self.wpPushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.wpPushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.wpPushButton_2.setObjectName("wpPushButton_2")
        self.horizontalLayout.addWidget(self.wpPushButton_2)
        self.wpPushButton_3 = QtWidgets.QPushButton(self.wpWidget_5)
        self.wpPushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.wpPushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.wpPushButton_3.setObjectName("wpPushButton_3")
        self.horizontalLayout.addWidget(self.wpPushButton_3)
        self.wpPushButton_4 = QtWidgets.QPushButton(self.wpWidget_5)
        self.wpPushButton_4.setMaximumSize(QtCore.QSize(25, 25))
        self.wpPushButton_4.setObjectName("wpPushButton_4")
        self.horizontalLayout.addWidget(self.wpPushButton_4)
        self.horizontalLayout_2.addWidget(self.wpWidget_5)
        self.wpLineEdit = QtWidgets.QLineEdit(self.wpWidget_3)
        self.wpLineEdit.setMinimumSize(QtCore.QSize(300, 28))
        self.wpLineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.wpLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(27, 27, 27);\n"
"    border-radius:12px;\n"
"    color:rgb(240, 240, 240);\n"
"    padding-left:15px;\n"
"    border: 1px solid rgba(255, 255, 255, 50);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgba(99, 173, 229, 150);\n"
"}")
        self.wpLineEdit.setObjectName("wpLineEdit")
        self.horizontalLayout_2.addWidget(self.wpLineEdit)
        self.wpWidget_6 = QtWidgets.QWidget(self.wpWidget_3)
        self.wpWidget_6.setMinimumSize(QtCore.QSize(0, 40))
        self.wpWidget_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wpWidget_6.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:17px;\n"
"    font-family:url(:/font/dripicons-v2.ttf);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(144, 144, 144, 30);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.wpWidget_6.setObjectName("wpWidget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wpWidget_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.wpWidget_6)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_3.setStyleSheet("font-family:dripicons-v2;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.wpWidget_6)
        self.pushButton_2.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.wpWidget_6)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.wpWidget_6)
        self.verticalLayout_2.addWidget(self.wpWidget_3)
        self.wpWidget_4 = QtWidgets.QWidget(self.wpWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wpWidget_4.sizePolicy().hasHeightForWidth())
        self.wpWidget_4.setSizePolicy(sizePolicy)
        self.wpWidget_4.setMinimumSize(QtCore.QSize(0, 30))
        self.wpWidget_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.wpWidget_4.setStyleSheet("QWidget#wpWidget_4{\n"
"    background-color:rgb(35, 34, 39);\n"
"}")
        self.wpWidget_4.setObjectName("wpWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wpWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.wpWidget_4)
        self.wpWidget_7 = QtWidgets.QWidget(self.wpWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wpWidget_7.sizePolicy().hasHeightForWidth())
        self.wpWidget_7.setSizePolicy(sizePolicy)
        self.wpWidget_7.setObjectName("wpWidget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wpWidget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(self.wpWidget_7)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.wpWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setStyleSheet("background-color:rgb(50,50,50);\n"
"QPushButton{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:17px;\n"
"    font-family:url(:/font/dripicons-v2.ttf);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(144, 144, 144, 30);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.page)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.zoom_label = QtWidgets.QLabel(self.widget_3)
        self.zoom_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.zoom_label.setObjectName("zoom_label")
        self.verticalLayout_6.addWidget(self.zoom_label)
        self.horizontalSlider = QtWidgets.QSlider(self.widget_3)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(80, 80))
        self.horizontalSlider.setStyleSheet("color: rgb(255, 5, 255);")
        self.horizontalSlider.setMinimum(30)
        self.horizontalSlider.setMaximum(500)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_6.addWidget(self.horizontalSlider)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.page)
        self.widget_4.setStyleSheet("QPushButton{\n"
"background-color:rgba(0, 0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(144, 144, 144, 30);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"\n"
"QCheckBox{\n"
"background-color:rgba(0, 0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:12px;\n"
"}\n"
"QCheckBox:hover{\n"
"    background-color:rgba(144, 144, 144, 30);\n"
"}\n"
"QCheckBox:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_8.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.setChecked(True)
        self.verticalLayout_8.addWidget(self.checkBox_2)
        self.Spacer_1 = QtWidgets.QLabel(self.widget_4)
        self.Spacer_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Spacer_1.setStyleSheet("color:rgba(172, 172, 172, 242)")
        self.Spacer_1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Spacer_1.setObjectName("Spacer_1")
        self.verticalLayout_8.addWidget(self.Spacer_1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_8.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_8.addWidget(self.pushButton_7)
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setStyleSheet("color:rgba(172, 172, 172, 242)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(self.pushButton_6)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.pushButton_4)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.wpWidget_7)
        self.verticalLayout.addWidget(self.wpWidget_2)

        self.retranslateUi(wpWidget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wpWidget)

    def retranslateUi(self, wpWidget):
        _translate = QtCore.QCoreApplication.translate
        wpWidget.setWindowTitle(_translate("wpWidget", "Form"))
        self.wpPushButton.setText(_translate("wpWidget", "l"))
        self.wpPushButton_2.setText(_translate("wpWidget", "m"))
        self.wpPushButton_3.setText(_translate("wpWidget", "Z"))
        self.wpPushButton_4.setText(_translate("wpWidget", ""))
        self.wpLineEdit.setPlaceholderText(_translate("wpWidget", "Type a URL"))
        self.pushButton_3.setText(_translate("wpWidget", "B"))
        self.pushButton_2.setText(_translate("wpWidget", ""))
        self.pushButton.setText(_translate("wpWidget", ""))
        self.zoom_label.setText(_translate("wpWidget", "Zoom:"))
        self.checkBox.setText(_translate("wpWidget", "Brainly Mode"))
        self.checkBox_2.setText(_translate("wpWidget", "Ignore Errors"))
        self.Spacer_1.setText(_translate("wpWidget", "________________"))
        self.pushButton_5.setText(_translate("wpWidget", "New Tab"))
        self.pushButton_7.setText(_translate("wpWidget", "New Window"))
        self.label_3.setText(_translate("wpWidget", "_______________"))
        self.pushButton_6.setText(_translate("wpWidget", "Settings"))
        self.pushButton_4.setText(_translate("wpWidget", "Exit"))
